networks:
  media-net:
    driver: bridge

services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000  # Change as needed
      - PGID=1000  # Change as needed
      - TZ=Australia/Brisbane  # Adjust timezone
    volumes:
      - /docker/sonarr/config:/config
      - /data:/data
    ports:
      - 8989:8989
    networks:
      - media-net
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Brisbane
    volumes:
      - /docker/radarr/config:/config
      - /data:/data
    ports:
      - 7878:7878
    networks:
      - media-net
    restart: unless-stopped

  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    container_name: nzbget
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Brisbane
    volumes:
      - /docker/nzbget/config:/config
      - /data:/data
    ports:
      - 6789:6789
    networks:
      - media-net
    restart: unless-stopped

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Brisbane
    volumes:
      - /docker/tautulli/config:/config
      - /data:/data
    ports:
      - 8181:8181
    networks:
      - media-net
    restart: unless-stopped

  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - TZ=Australia/Brisbane
      - LOG_LEVEL=info
    ports:
      - 5055:5055
    volumes:
      - /docker/overseerr/config:/app/config
    networks:
      - media-net
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --interval 86400
    networks:
      - media-net
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Brisbane
    volumes:
      - /docker/prowlarr/config:/config
    ports:
      - 9696:9696
    networks:
      - media-net
    restart: unless-stopped
