#!/bin/bash

# Install Flatpack 
#sudo apt install flatpak
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

# Install Flatpacks
flatpak install -y flathub com.spotify.Client
flatpak install -y flathub org.videolan.VLC
flatpak install -y flathub com.visualstudio.code
flatpak install -y flathub com.dropbox.Client
flatpak install -y flathub org.filezillaproject.Filezilla
flatpak install -y flathub io.github.shiftey.Desktop
flatpak install -y flathub org.gnome.Lollypop
flatpak install -y flathub com.github.Bleuzen.FFaudioConverter
flatpak install -y flathub com.makemkv.MakeMKV
flatpak install -y flathub com.atlauncher.ATLauncher
flatpak install -y flathub com.moonlight_stream.Moonlight
flatpak install -y flathub com.brave.Browser
flatpak install -y flathub org.deluge_torrent.deluge
flatpak install -y flathub com.ultimaker.cura

# Reboot
sudo reboot
